# Medical Examiner Case Archives

Cook County (Chicago) medical examiner records, taken from [here](https://datacatalog.cookcountyil.gov/Public-Safety/Medical-Examiner-Case-Archive/cjeq-bs86) after discovery via [Data is Plural](https://tinyletter.com/data-is-plural).

## Do your importing/setup

In [2]:
import pandas as pd
import numpy as np

%matplotlib inline

## Read in the data, check its row count and column types

In [3]:
Medical_case = pd.read_csv('case-archive-encoded.csv', na_values=[-1, "NaN"])
Medical_case.head()

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
0,ME2017-04255,09/10/2017 08:28:00 PM,09/10/2017 08:51:00 PM,51.0,1.0,5.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20468,NaN
1,ME2018-02149,05/05/2018 06:30:00 AM,05/05/2018 06:41:00 AM,65.0,1.0,5.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2110 W. 21ST PL #1,CHICAGO,-87.678845,41.853279,77827,"(41.8532787, -87.6788449)"
2,ME2018-02154,04/26/2018 08:29:00 AM,05/05/2018 04:45:00 AM,95.0,1.0,5.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20704 S Woodlawn Ct,FRANKFORT,NaN,NaN,77839,NaN
3,ME2018-02156,05/05/2018 12:00:00 PM,05/05/2018 12:25:00 PM,64.0,0.0,5.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4008 W. BERTEAU AVENUE, APT #1",CHICAGO,-87.728177,41.957468,77823,"(41.9574677, -87.7281769)"
4,ME2018-02158,05/05/2018 09:30:00 AM,05/05/2018 09:50:00 AM,61.0,1.0,2.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3947 W. LEXINGTON STREET,CHICAGO,-87.724739,41.871451,77822,"(41.8714515, -87.7247386)"

In [4]:
Medical_case.dtypes

Case Number              object
Date of Incident         object
Date of Death            object
Age                     float64
Gender                  float64
Race                    float64
Latino                     bool
Manner of Death          object
Primary Cause            object
Primary Cause Line B     object
Primary Cause Line C     object
Secondary Cause          object
Gun Related              object
Opioid Related           object
Incident Address         object
Incident City            object
longitude               float64
latitude                float64
OBJECTID                  int64
location                 object
dtype: object

In [5]:
Medical_case.shape

(22634, 20)

In [6]:
#GENDER REPLACE

Medical_case['Gender'] = Medical_case.Gender.replace({
    -1: 'Data missing',
    0: 'Female',
    1: 'Male',
    2:'Unknown'
})
Medical_case

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
0,ME2017-04255,09/10/2017 08:28:00 PM,09/10/2017 08:51:00 PM,51.0,Male,5.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20468,NaN
1,ME2018-02149,05/05/2018 06:30:00 AM,05/05/2018 06:41:00 AM,65.0,Male,5.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2110 W. 21ST PL #1,CHICAGO,-87.678845,41.853279,77827,"(41.8532787, -87.6788449)"
2,ME2018-02154,04/26/2018 08:29:00 AM,05/05/2018 04:45:00 AM,95.0,Male,5.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20704 S Woodlawn Ct,FRANKFORT,NaN,NaN,77839,NaN
3,ME2018-02156,05/05/2018 12:00:00 PM,05/05/2018 12:25:00 PM,64.0,Female,5.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4008 W. BERTEAU AVENUE, APT #1",CHICAGO,-87.728177,41.957468,77823,"(41.9574677, -87.7281769)"
4,ME2018-02158,05/05/2018 09:30:00 AM,05/05/2018 09:50:00 AM,61.0,Male,2.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3947 W. LEXINGTON STREET,CHICAGO,-87.724739,41.871451,77822,"(41.8714515, -87.7247386)"
5,ME2018-02153,03/20/2018 12:00:00 AM,05/05/2018 01:28:00 AM,28.0,Male,2.0,False,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77903,NaN
6,ME2017-00971,02/25/2017 07:48:00 AM,02/25/2017 09:20:00 AM,55.0,Male,5.0,False,UNDETERMINED,GUNSHOT WOUND TO HEAD,NaN,NaN,NaN,True,NaN,209 E. LAKE SHORE DRIVE,CHICAGO,-87.621421,41.900571,77930,"(41.900571, -87.6214206)"
7,ME2018-02147,05/04/2018 10:04:00 PM,05/04/2018 10:25:00 PM,47.0,Male,2.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,1905 S. SPAULDING #1,CHICAGO,-87.707465,41.855148,78042,"(41.855148, -87.707465)"
8,ME2018-02152,05/05/2018 01:47:00 AM,05/05/2018 02:54:00 AM,3.0,Male,5.0,True,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,1012 N. AVERS AVENUE APT#2,CHICAGO,NaN,NaN,78299,NaN
9,ME2018-02151,05/05/2018 06:00:00 AM,05/05/2018 06:35:00 AM,62.0,Male,2.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,910 W 76TH 3RD FLOOR,CHICAGO,-87.647042,41.756124,78337,"(41.7561236, -87.6470422)"
10,ME2018-02148,05/04/2018 11:55:00 PM,05/05/2018 12:16:00 AM,55.0,Male,2.0,False,SUICIDE,GUNSHOT WOUND OF HEAD,NaN,NaN,NaN,True,NaN,"300 NORTH STATE, APT 6021",CHICAGO,-87.629078,41.887930,78480,"(41.8879298, -87.6290778)"
11,ME2014-00679,09/24/2014 09:06:00 PM,09/25/2014 01:52:00 AM,52.0,Male,5.0,False,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,NaN,NaN,724 Railroad Street,JOLIET,NaN,NaN,62692,NaN
12,ME2018-01106,03/01/2018 01:58:00 PM,03/01/2018 05:00:00 PM,37.0,Male,5.0,False,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,NaN,NaN,290 EASTBOUND AT MILE MARKER POST 14,BELLWOOD,NaN,NaN,60932,NaN
13,ME2018-01125,03/02/2018 10:45:00 PM,03/02/2018 11:09:00 PM,47.0,Male,2.0,False,NATURAL,COMPLICATIONS OF MORBID OBESITY,NaN,NaN,NaN,NaN,NaN,1132 TROOST AVENUE APT 101,FOREST PARK,-87.816930,41.865348,77748,"(41.8653484, -87.8169297)"
14,ME2018-01126,03/03/2018 01:15:00 AM,03/03/2018 02:16:00 AM,37.0,Male,5.0,True,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,NaN,159TH AND FINCH,HARVEY,-87.640104,41.600898,58723,"(41.6008977, -87.6401039)"
15,ME2018-01127,03/03/2018 02:15:00 AM,03/03/2018 02:24:00 AM,37.0,Male,5.0,False,ACCIDENT,"COMBINED DRUG (COCAINE, HEROIN, FENTANYL) TOXI...",NaN,NaN,NaN,NaN,True,6547 W. 111TH APT W-27,WORTH,-87.781732,41.689640,63784,"(41.6896403, -87.7817317)"
16,ME2018-01128,03/03/2018 02:51:00 AM,03/03/2018 03:13:00 AM,31.0,Male,2.0,False,HOMICIDE,MULTIPLE SHARP FORCE INJURIES,NaN,NaN,NaN,NaN,NaN,6916 S. MICHIGAN AVENUE,CHICAGO,-87.622115,41.768692,77583,"(41.7686918, -87.6221153)"
17,ME2018-01130,02/17/2018 12:00:00 AM,03/02/2018 11:31:00 PM,66.0,Male,5.0,False,ACCIDENT,CLOSED HEAD INJURIES,NaN,NaN,CHRONIC ETHANOLISM,NaN,NaN,6238 w. 26th #205,BERWYN,-87.780093,41.843267,57453,"(41.8432672, -87.7800927)"
18,ME2018-01135,03/03/2018 09:30:00 AM,03/03/2018 10:05:00 AM,55.0,Male,2.0,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,NaN,10034 S. MICHICAGN AVE. APT 2,NaN,NaN,NaN,71064,NaN
19,ME2018-02093,05/01/2018 11:00:00 PM,05/01/2018 10:22:00 PM,31.0,Male,2.0,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,NaN,4811 W. WASHINGTON BLVD.,CHICAGO,-87.745651,41.881767,77825,"(41.8817674, -87.7456512)"
20,ME2018-02096,05/02/2018 02:58:00 AM,05/02/2018 03:41:00 AM,69.0,Male,5.0,False,HOMICIDE,MULTIPLE STAB AND INCISED WOUNDS,NaN,NaN,NaN,NaN,NaN,5300 S. SOUTH SHORE DRIVE UNIT 43,CHICAGO,NaN,NaN,77978,NaN
21,ME2018-02125,05/01/2018 01:00:00 PM,05/03/2018 01:52:00 PM,49.0,Female,5.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,1653 W Congress Pkwy,NaN,-87.667945,41.875108,78013,"(41.8751081, -87.6679448)"
22,ME2018-02095,05/01/2018 11:00:00 PM,05/01/2018 11:59:00 PM,37.0,Male,2.0,False,HOMICIDE,STAB WOUND OF CHEST,NaN,NaN,NaN,NaN,NaN,1440 EMBASSY LANE,FORD HEIGHTS,-87.585216,41.513330,78840,"(41.5133297, -87.5852155)"
23,ME2014-00102,08/17/2014 12:00:00 PM,08/17/2014 03:11:00 PM,39.0,Female,2.0,False,SUICIDE,MULTIPLE INJURIES,NaN,NaN,NaN,NaN,NaN,"23443 WESTERN AVENUE, APT. 72",PARK FOREST,NaN,NaN,63896,NaN
24,ME2014-00339,09/02/2014 08:14:00 PM,09/03/2014 04:13:00 AM,54.0,Male,5.0,False,ACCIDENT,CEREBRAL INJURIES,NaN,NaN,NaN,NaN,NaN,IRVING PARK RD AT SALT CREEK,WOOD DALE,NaN,NaN,62191,NaN
25,ME2018-02136,05/03/2018 09:05:00 PM,05/03/2018 09:47:00 PM,53.0,Male,2.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,"8301 SOUTH 88TH AVE, APT 412",JUSTICE,NaN,NaN,77854,NaN
26,ME2018-02166,04/30/2018 03:00:00 PM,05/06/2018 06:09:00 AM,66.0,Male,5.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1815 N. KARLOV,CHICAGO,-87.728637,41.914066,77857,"(41.9140656, -87.7286374)"
27,ME2018-02131,05/03/2018 07:15:00 PM,05/03/2018 08:00:00 PM,48.0,Male,5.0,False,NATURAL,ATHEROSCLEROTIC AND HYPERTENSIVE CARDIOVASCULA...,NaN,NaN,OBESITY,NaN,NaN,2631 West Rascher Avenue,CHICAGO,-87.695479,41.980215,77843,"(41.9802154, -87.6954789)"
28,ME2018-02134,05/03/2018 06:20:00 PM,05/03/2018 07:01:00 PM,76.0,Male,5.0,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,DIABETES MELLITUS AND OBESITY,NaN,NaN,8108 ODELL AVENUE,BRIDGEVIEW,-87.803607,41.744014,77849,"(41.7440145, -87.8036075)"
29,ME2018-02177,05/07/2018 04:16:00 AM,05/07/2018 05:07:00 AM,49.0,Male,5.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,411 Carrick Rd,MATTESON,-87.729948,41.518675,77881,"(41.5186752, -87.7299482)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22604,ME2018-02088,05/01/2018 05:15:00 PM,05/01/2018 06:50:00 PM,50.0,Male,5.0,True,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,"DIABETES MELLITUS, CIRRHOSIS OF THE LIVER",NaN,NaN,"2832 WEST CERMAK, UNIT 2F",CHICAGO,-87.696780,41.852127,70244,"(41.8521269, -87.6967797)"
22605,ME2018-02089,05/01/2018 08:16:00 PM,01/01/1970 12:00:00 AM,NaN,NaN,NaN,False,NaN,NON-HUMAN REMAINS,NaN,NaN,NaN,NaN,NaN,729 E OAKWOOD BLVD,CHICAGO,-87.608927,41.822673,75628,"(41.8226731, -87.608927)"
22606,ME2018-02090,05/01/2018 07:20:00 PM,05/01/2018 06:29:00 PM,48.0,Female,2.0,False,NATURAL,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,NaN,NaN,CHRONIC KIDNEY DISEASE,NaN,NaN,201 W. 69TH STREET,CHICAGO,-87.630248,41.768766,72642,"(41.768766, -87.6302482)"
22607,ME2018-02092,05/01/2018 10:30:00 PM,05/01/2018 10:38:00 PM,48.0,Male,2.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,7846 S Kingston,CHICAGO,-87.562686,41.752230,77795,"(41.7522303, -87.5626855)"
22608,ME2018-02074,05/01/2018 08:33:00 AM,05/01/2018 09:03:00 AM,62.0,Male,2.0,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,NaN,2901 S. Michigan Avenue #504 South Commons,CHICAGO,-87.622834,41.841718,77971,"(41.8417184, -87.6228345)"
22609,ME2018-02099,05/02/2018 09:45:00 AM,05/02/2018 09:49:00 AM,30.0,Male,2.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,250 N. Western Avenue,NaN,-87.686970,41.886049,77976,"(41.8860494, -87.6869702)"
22610,ME2018-02098,05/02/2018 06:00:00 AM,05/02/2018 06:39:00 AM,56.0,Male,2.0,False,HOMICIDE,MULTIPLE BLUNT FORCE INJURIES,NaN,NaN,NaN,NaN,NaN,216 w. 147TH STREET,HARVEY,-87.668955,41.622493,78086,"(41.6224931, -87.6689548)"
22611,ME2018-02091,05/01/2018 08:00:00 PM,05/01/2018 08:45:00 PM,55.0,Female,5.0,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CIRRHOSIS OF UNKNOWN ETIOLOGY,NaN,NaN,1755 HENLEY ST #2N,GLENVIEW,-87.802212,42.070070,78280,"(42.0700695, -87.8022124)"
22612,ME2018-02081,05/01/2018 12:40:00 PM,05/01/2018 12:53:00 PM,61.0,Male,2.0,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,NaN,"527 W. 14TH PLACE, PACIFIC GARDEN MISSION",CHICAGO,-87.640188,41.862401,78381,"(41.8624014, -87.640188)"
22613,ME2018-02094,05/01/2018 09:10:00 PM,05/01/2018 10:12:00 PM,54.0,Male,5.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,9858 IRVING PARK ROAD,SCHILLER PARK,-87.873368,41.956126,78475,"(41.9561261, -87.8733682)"
22614,ME2018-02097,05/02/2018 06:00:00 AM,05/02/2018 06:49:00 AM,53.0,Female,2.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,2373 E 70TH ST,CHICAGO,-87.567272,41.768022,78635,"(41.768022, -87.5672724)"
22615,ME2018-02101,05/02/2018 07:00:00 AM,05/02/2018 10:03:00 AM,43.0,Male,5.0,True,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,9558 SHERMER ROAD,MORTON GROVE,-87.811772,42.054776,77791,"(42.0547758, -87.8117716)"
22616,ME2018-02103,04/30/2018 12:00:00 AM,05/02/2018 01:21:00 PM,77.0,Male,5.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,"1001 Elm Street, South West",DEMOTTE,NaN,NaN,57915,NaN
22617,ME2018-02109,05/02/2018 05:00:00 PM,05/02/2018 05:18:00 PM,59.0,Male,5.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,529 RIDGEWOOD ROAD,ELK GROVE VILLAGE,-87.982034,42.018169,77811,"(42.0181695, -87.982034)"
22618,ME2018-02110,05/02/2018 07:50:00 PM,05/02/2018 08:14:00 PM,72.0,Male,2.0,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,NaN,"1341 W. 92ND STREET, UNIT #2",CHICAGO,-87.657078,41.726717,77789,"(41.7267165, -87.6570785)"
22619,ME2018-02111,05/02/2018 09:17:00 PM,05/02/2018 09:23:00 PM,91.0,Male,5.0,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,NaN,2058 W. Hutchinson,CHICAGO,-87.681238,41.958973,67932,"(41.9589732, -87.6812383)"
22620,ME2018-02116,04/21/2018 10:00:00 PM,05/03/2018 12:15:00 PM,88.0,Male,2.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7140 S. MARSHFIELD AVENUE,CHICAGO,-87.665268,41.763703,59566,"(41.7637034, -87.6652684)"
22621,ME2018-02118,05/03/2018 08:00:00 AM,05/03/2018 09:57:00 AM,29.0,Female,5.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,9000 West College Park way,PALOS HILLS,-87.837735,41.689509,77788,"(41.6895094, -87.837735)"
22622,ME2018-02124,05/03/2018 03:09:00 PM,05/03/2018 11:33:00 AM,60.0,Female,2.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8419 S ESCANABA AVE,NaN,-87.553689,41.742221,67087,"(41.7422211, -87.5536891)"
22623,ME2018-02126,05/03/2018 02:01:00 PM,05/03/2018 02:37:00 PM,61.0,Male,5.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,1512 SILVER LANE APT #1,PALATINE,-88.007342,42.136492,77779,"(42.1364923, -88.0073415)"
22624,ME2018-02100,05/02/2018 08:08:00 AM,05/02/2018 08:21:00 AM,85.0,Male,2.0,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,NaN,1127 Miller Lane;,BUFFALO GROVE,-87.978407,42.134728,77891,"(42.1347284, -87.9784066)"
22625,ME2018-02102,05/02/2018 12:10:00 PM,05/02/2018 12:19:00 PM,73.0,Male,5.0,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,NaN,"549 W. ALDINE AVENUE, UNIT #203",CHICAGO,-87.643876,41.941953,77939,"(41.9419529, -87.6438762)"
22626,ME2018-02115,05/03/2018 08:32:00 AM,05/03/2018 08:52:00 AM,0.0,Female,2.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,16102 RICHMOND AVE,MARKHAM,-87.687286,41.597228,78018,"(41.5972276, -87.687286)"
22627,ME2018-02120,05/03/2018 11:00:00 AM,05/03/2018 12:18:00 PM,32.0,Female,2.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,9158 S. HARVARD AVENUE,CHICAGO,-87.632148,41.727769,77985,"(41.7277694, -87.6321484)"
22628,ME2018-02123,05/03/2018 01:15:00 PM,05/03/2018 01:51:00 PM,42.0,Male,2.0,False,HOMICIDE,GUNSHOT WOUND OF RIGHT BUTTOCK,NaN,NaN,NaN,True,NaN,8159 SOUTH CORNELL AVENUE,CHICAGO,-87.583910,41.746488,78103,"(41.7464877, -87.5839097)"
22629,ME2018-02104,12/31/2017 11:23:00 PM,05/02/2018 01:59:00 PM,34.0,Male,5.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,5535 NORTH LINCOLN AVENUE,CHICAGO,-87.693476,41.982498,78129,"(41.9824976, -87.6934761)"
22630,ME2018-02122,05/03/2018 12:29:00 PM,05/03/2018 12:39:00 PM,94.0,Male,5.0,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,"CORONARY ARTERY DISEASE, HYPERTENSION, DIABETE...",NaN,NaN,16416 EVANS AVENUE,SOUTH HOLLAND,-87.600994,41.596634,78272,"(41.5966344, -87.6009945)"
22631,ME2018-02114,05/03/2018 08:09:00 AM,05/03/2018 08:19:00 AM,68.0,Male,0.0,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,15243 3RD AVE.,PHOENIX,-87.631849,41.611941,78496,"(41.6119409, -87.6318491)"
22632,ME2018-02105,05/02/2018 02:00:00 PM,05/02/2018 02:25:00 PM,50.0,Male,5.0,False,SUICIDE,GUNSHOT WOUND OF HEAD,NaN,NaN,NaN,True,NaN,640 CUMBERLAND ST,HOFFMAN ESTATES,-88.079340,42.039490,78745,"(42.0394902, -88.07934)"
22633,ME2018-02107,05/02/2018 04:53:00 PM,05/02/2018 05:11:00 PM,57.0,Male,2.0,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CHRONIC OBSTRUCTIVE PULMONARY DISEASE,NaN,NaN,3914 212 PL,MATTESON,-87.711457,41.504114,78828,"(41.5041136, -87.7114567)"

In [7]:
#RACE REPLACE

Medical_case['Race'] = Medical_case.Race.replace({
    -1: 'Data missing',
    0: 'American Indian',
    1: 'Asian',
    2:'Black',
    3:'Other',
    4:'Unknown',
    5:'White'
})
Medical_case

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
0,ME2017-04255,09/10/2017 08:28:00 PM,09/10/2017 08:51:00 PM,51.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20468,NaN
1,ME2018-02149,05/05/2018 06:30:00 AM,05/05/2018 06:41:00 AM,65.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2110 W. 21ST PL #1,CHICAGO,-87.678845,41.853279,77827,"(41.8532787, -87.6788449)"
2,ME2018-02154,04/26/2018 08:29:00 AM,05/05/2018 04:45:00 AM,95.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20704 S Woodlawn Ct,FRANKFORT,NaN,NaN,77839,NaN
3,ME2018-02156,05/05/2018 12:00:00 PM,05/05/2018 12:25:00 PM,64.0,Female,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4008 W. BERTEAU AVENUE, APT #1",CHICAGO,-87.728177,41.957468,77823,"(41.9574677, -87.7281769)"
4,ME2018-02158,05/05/2018 09:30:00 AM,05/05/2018 09:50:00 AM,61.0,Male,Black,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3947 W. LEXINGTON STREET,CHICAGO,-87.724739,41.871451,77822,"(41.8714515, -87.7247386)"
5,ME2018-02153,03/20/2018 12:00:00 AM,05/05/2018 01:28:00 AM,28.0,Male,Black,False,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77903,NaN
6,ME2017-00971,02/25/2017 07:48:00 AM,02/25/2017 09:20:00 AM,55.0,Male,White,False,UNDETERMINED,GUNSHOT WOUND TO HEAD,NaN,NaN,NaN,True,NaN,209 E. LAKE SHORE DRIVE,CHICAGO,-87.621421,41.900571,77930,"(41.900571, -87.6214206)"
7,ME2018-02147,05/04/2018 10:04:00 PM,05/04/2018 10:25:00 PM,47.0,Male,Black,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,1905 S. SPAULDING #1,CHICAGO,-87.707465,41.855148,78042,"(41.855148, -87.707465)"
8,ME2018-02152,05/05/2018 01:47:00 AM,05/05/2018 02:54:00 AM,3.0,Male,White,True,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,1012 N. AVERS AVENUE APT#2,CHICAGO,NaN,NaN,78299,NaN
9,ME2018-02151,05/05/2018 06:00:00 AM,05/05/2018 06:35:00 AM,62.0,Male,Black,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,910 W 76TH 3RD FLOOR,CHICAGO,-87.647042,41.756124,78337,"(41.7561236, -87.6470422)"
10,ME2018-02148,05/04/2018 11:55:00 PM,05/05/2018 12:16:00 AM,55.0,Male,Black,False,SUICIDE,GUNSHOT WOUND OF HEAD,NaN,NaN,NaN,True,NaN,"300 NORTH STATE, APT 6021",CHICAGO,-87.629078,41.887930,78480,"(41.8879298, -87.6290778)"
11,ME2014-00679,09/24/2014 09:06:00 PM,09/25/2014 01:52:00 AM,52.0,Male,White,False,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,NaN,NaN,724 Railroad Street,JOLIET,NaN,NaN,62692,NaN
12,ME2018-01106,03/01/2018 01:58:00 PM,03/01/2018 05:00:00 PM,37.0,Male,White,False,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,NaN,NaN,290 EASTBOUND AT MILE MARKER POST 14,BELLWOOD,NaN,NaN,60932,NaN
13,ME2018-01125,03/02/2018 10:45:00 PM,03/02/2018 11:09:00 PM,47.0,Male,Black,False,NATURAL,COMPLICATIONS OF MORBID OBESITY,NaN,NaN,NaN,NaN,NaN,1132 TROOST AVENUE APT 101,FOREST PARK,-87.816930,41.865348,77748,"(41.8653484, -87.8169297)"
14,ME2018-01126,03/03/2018 01:15:00 AM,03/03/2018 02:16:00 AM,37.0,Male,White,True,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,NaN,159TH AND FINCH,HARVEY,-87.640104,41.600898,58723,"(41.6008977, -87.6401039)"
15,ME2018-01127,03/03/2018 02:15:00 AM,03/03/2018 02:24:00 AM,37.0,Male,White,False,ACCIDENT,"COMBINED DRUG (COCAINE, HEROIN, FENTANYL) TOXI...",NaN,NaN,NaN,NaN,True,6547 W. 111TH APT W-27,WORTH,-87.781732,41.689640,63784,"(41.6896403, -87.7817317)"
16,ME2018-01128,03/03/2018 02:51:00 AM,03/03/2018 03:13:00 AM,31.0,Male,Black,False,HOMICIDE,MULTIPLE SHARP FORCE INJURIES,NaN,NaN,NaN,NaN,NaN,6916 S. MICHIGAN AVENUE,CHICAGO,-87.622115,41.768692,77583,"(41.7686918, -87.6221153)"
17,ME2018-01130,02/17/2018 12:00:00 AM,03/02/2018 11:31:00 PM,66.0,Male,White,False,ACCIDENT,CLOSED HEAD INJURIES,NaN,NaN,CHRONIC ETHANOLISM,NaN,NaN,6238 w. 26th #205,BERWYN,-87.780093,41.843267,57453,"(41.8432672, -87.7800927)"
18,ME2018-01135,03/03/2018 09:30:00 AM,03/03/2018 10:05:00 AM,55.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,NaN,10034 S. MICHICAGN AVE. APT 2,NaN,NaN,NaN,71064,NaN
19,ME2018-02093,05/01/2018 11:00:00 PM,05/01/2018 10:22:00 PM,31.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,NaN,4811 W. WASHINGTON BLVD.,CHICAGO,-87.745651,41.881767,77825,"(41.8817674, -87.7456512)"
20,ME2018-02096,05/02/2018 02:58:00 AM,05/02/2018 03:41:00 AM,69.0,Male,White,False,HOMICIDE,MULTIPLE STAB AND INCISED WOUNDS,NaN,NaN,NaN,NaN,NaN,5300 S. SOUTH SHORE DRIVE UNIT 43,CHICAGO,NaN,NaN,77978,NaN
21,ME2018-02125,05/01/2018 01:00:00 PM,05/03/2018 01:52:00 PM,49.0,Female,White,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,1653 W Congress Pkwy,NaN,-87.667945,41.875108,78013,"(41.8751081, -87.6679448)"
22,ME2018-02095,05/01/2018 11:00:00 PM,05/01/2018 11:59:00 PM,37.0,Male,Black,False,HOMICIDE,STAB WOUND OF CHEST,NaN,NaN,NaN,NaN,NaN,1440 EMBASSY LANE,FORD HEIGHTS,-87.585216,41.513330,78840,"(41.5133297, -87.5852155)"
23,ME2014-00102,08/17/2014 12:00:00 PM,08/17/2014 03:11:00 PM,39.0,Female,Black,False,SUICIDE,MULTIPLE INJURIES,NaN,NaN,NaN,NaN,NaN,"23443 WESTERN AVENUE, APT. 72",PARK FOREST,NaN,NaN,63896,NaN
24,ME2014-00339,09/02/2014 08:14:00 PM,09/03/2014 04:13:00 AM,54.0,Male,White,False,ACCIDENT,CEREBRAL INJURIES,NaN,NaN,NaN,NaN,NaN,IRVING PARK RD AT SALT CREEK,WOOD DALE,NaN,NaN,62191,NaN
25,ME2018-02136,05/03/2018 09:05:00 PM,05/03/2018 09:47:00 PM,53.0,Male,Black,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,"8301 SOUTH 88TH AVE, APT 412",JUSTICE,NaN,NaN,77854,NaN
26,ME2018-02166,04/30/2018 03:00:00 PM,05/06/2018 06:09:00 AM,66.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1815 N. KARLOV,CHICAGO,-87.728637,41.914066,77857,"(41.9140656, -87.7286374)"
27,ME2018-02131,05/03/2018 07:15:00 PM,05/03/2018 08:00:00 PM,48.0,Male,White,False,NATURAL,ATHEROSCLEROTIC AND HYPERTENSIVE CARDIOVASCULA...,NaN,NaN,OBESITY,NaN,NaN,2631 West Rascher Avenue,CHICAGO,-87.695479,41.980215,77843,"(41.9802154, -87.6954789)"
28,ME2018-02134,05/03/2018 06:20:00 PM,05/03/2018 07:01:00 PM,76.0,Male,White,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,DIABETES MELLITUS AND OBESITY,NaN,NaN,8108 ODELL AVENUE,BRIDGEVIEW,-87.803607,41.744014,77849,"(41.7440145, -87.8036075)"
29,ME2018-02177,05/07/2018 04:16:00 AM,05/07/2018 05:07:00 AM,49.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,411 Carrick Rd,MATTESON,-87.729948,41.518675,77881,"(41.5186752, -87.7299482)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22604,ME2018-02088,05/01/2018 05:15:00 PM,05/01/2018 06:50:00 PM,50.0,Male,White,True,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,"DIABETES MELLITUS, CIRRHOSIS OF THE LIVER",NaN,NaN,"2832 WEST CERMAK, UNIT 2F",CHICAGO,-87.696780,41.852127,70244,"(41.8521269, -87.6967797)"
22605,ME2018-02089,05/01/2018 08:16:00 PM,01/01/1970 12:00:00 AM,NaN,NaN,NaN,False,NaN,NON-HUMAN REMAINS,NaN,NaN,NaN,NaN,NaN,729 E OAKWOOD BLVD,CHICAGO,-87.608927,41.822673,75628,"(41.8226731, -87.608927)"
22606,ME2018-02090,05/01/2018 07:20:00 PM,05/01/2018 06:29:00 PM,48.0,Female,Black,False,NATURAL,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,NaN,NaN,CHRONIC KIDNEY DISEASE,NaN,NaN,201 W. 69TH STREET,CHICAGO,-87.630248,41.768766,72642,"(41.768766, -87.6302482)"
22607,ME2018-02092,05/01/2018 10:30:00 PM,05/01/2018 10:38:00 PM,48.0,Male,Black,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,7846 S Kingston,CHICAGO,-87.562686,41.752230,77795,"(41.7522303, -87.5626855)"
22608,ME2018-02074,05/01/2018 08:33:00 AM,05/01/2018 09:03:00 AM,62.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,NaN,2901 S. Michigan Avenue #504 South Commons,CHICAGO,-87.622834,41.841718,77971,"(41.8417184, -87.6228345)"
22609,ME2018-02099,05/02/2018 09:45:00 AM,05/02/2018 09:49:00 AM,30.0,Male,Black,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,250 N. Western Avenue,NaN,-87.686970,41.886049,77976,"(41.8860494, -87.6869702)"
22610,ME2018-02098,05/02/2018 06:00:00 AM,05/02/2018 06:39:00 AM,56.0,Male,Black,False,HOMICIDE,MULTIPLE BLUNT FORCE INJURIES,NaN,NaN,NaN,NaN,NaN,216 w. 147TH STREET,HARVEY,-87.668955,41.622493,78086,"(41.6224931, -87.6689548)"
22611,ME2018-02091,05/01/2018 08:00:00 PM,05/01/2018 08:45:00 PM,55.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CIRRHOSIS OF UNKNOWN ETIOLOGY,NaN,NaN,1755 HENLEY ST #2N,GLENVIEW,-87.802212,42.070070,78280,"(42.0700695, -87.8022124)"
22612,ME2018-02081,05/01/2018 12:40:00 PM,05/01/2018 12:53:00 PM,61.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,NaN,"527 W. 14TH PLACE, PACIFIC GARDEN MISSION",CHICAGO,-87.640188,41.862401,78381,"(41.8624014, -87.640188)"
22613,ME2018-02094,05/01/2018 09:10:00 PM,05/01/2018 10:12:00 PM,54.0,Male,White,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,9858 IRVING PARK ROAD,SCHILLER PARK,-87.873368,41.956126,78475,"(41.9561261, -87.8733682)"
22614,ME2018-02097,05/02/2018 06:00:00 AM,05/02/2018 06:49:00 AM,53.0,Female,Black,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,2373 E 70TH ST,CHICAGO,-87.567272,41.768022,78635,"(41.768022, -87.5672724)"
22615,ME2018-02101,05/02/2018 07:00:00 AM,05/02/2018 10:03:00 AM,43.0,Male,White,True,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,9558 SHERMER ROAD,MORTON GROVE,-87.811772,42.054776,77791,"(42.0547758, -87.8117716)"
22616,ME2018-02103,04/30/2018 12:00:00 AM,05/02/2018 01:21:00 PM,77.0,Male,White,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,"1001 Elm Street, South West",DEMOTTE,NaN,NaN,57915,NaN
22617,ME2018-02109,05/02/2018 05:00:00 PM,05/02/2018 05:18:00 PM,59.0,Male,White,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,529 RIDGEWOOD ROAD,ELK GROVE VILLAGE,-87.982034,42.018169,77811,"(42.0181695, -87.982034)"
22618,ME2018-02110,05/02/2018 07:50:00 PM,05/02/2018 08:14:00 PM,72.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,NaN,"1341 W. 92ND STREET, UNIT #2",CHICAGO,-87.657078,41.726717,77789,"(41.7267165, -87.6570785)"
22619,ME2018-02111,05/02/2018 09:17:00 PM,05/02/2018 09:23:00 PM,91.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,NaN,2058 W. Hutchinson,CHICAGO,-87.681238,41.958973,67932,"(41.9589732, -87.6812383)"
22620,ME2018-02116,04/21/2018 10:00:00 PM,05/03/2018 12:15:00 PM,88.0,Male,Black,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7140 S. MARSHFIELD AVENUE,CHICAGO,-87.665268,41.763703,59566,"(41.7637034, -87.6652684)"
22621,ME2018-02118,05/03/2018 08:00:00 AM,05/03/2018 09:57:00 AM,29.0,Female,White,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,9000 West College Park way,PALOS HILLS,-87.837735,41.689509,77788,"(41.6895094, -87.837735)"
22622,ME2018-02124,05/03/2018 03:09:00 PM,05/03/2018 11:33:00 AM,60.0,Female,Black,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8419 S ESCANABA AVE,NaN,-87.553689,41.742221,67087,"(41.7422211, -87.5536891)"
22623,ME2018-02126,05/03/2018 02:01:00 PM,05/03/2018 02:37:00 PM,61.0,Male,White,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,1512 SILVER LANE APT #1,PALATINE,-88.007342,42.136492,77779,"(42.1364923, -88.0073415)"
22624,ME2018-02100,05/02/2018 08:08:00 AM,05/02/2018 08:21:00 AM,85.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,NaN,1127 Miller Lane;,BUFFALO GROVE,-87.978407,42.134728,77891,"(42.1347284, -87.9784066)"
22625,ME2018-02102,05/02/2018 12:10:00 PM,05/02/2018 12:19:00 PM,73.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,NaN,"549 W. ALDINE AVENUE, UNIT #203",CHICAGO,-87.643876,41.941953,77939,"(41.9419529, -87.6438762)"
22626,ME2018-02115,05/03/2018 08:32:00 AM,05/03/2018 08:52:00 AM,0.0,Female,Black,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,16102 RICHMOND AVE,MARKHAM,-87.687286,41.597228,78018,"(41.5972276, -87.687286)"
22627,ME2018-02120,05/03/2018 11:00:00 AM,05/03/2018 12:18:00 PM,32.0,Female,Black,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,9158 S. HARVARD AVENUE,CHICAGO,-87.632148,41.727769,77985,"(41.7277694, -87.6321484)"
22628,ME2018-02123,05/03/2018 01:15:00 PM,05/03/2018 01:51:00 PM,42.0,Male,Black,False,HOMICIDE,GUNSHOT WOUND OF RIGHT BUTTOCK,NaN,NaN,NaN,True,NaN,8159 SOUTH CORNELL AVENUE,CHICAGO,-87.583910,41.746488,78103,"(41.7464877, -87.5839097)"
22629,ME2018-02104,12/31/2017 11:23:00 PM,05/02/2018 01:59:00 PM,34.0,Male,White,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,5535 NORTH LINCOLN AVENUE,CHICAGO,-87.693476,41.982498,78129,"(41.9824976, -87.6934761)"
22630,ME2018-02122,05/03/2018 12:29:00 PM,05/03/2018 12:39:00 PM,94.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,"CORONARY ARTERY DISEASE, HYPERTENSION, DIABETE...",NaN,NaN,16416 EVANS AVENUE,SOUTH HOLLAND,-87.600994,41.596634,78272,"(41.5966344, -87.6009945)"
22631,ME2018-02114,05/03/2018 08:09:00 AM,05/03/2018 08:19:00 AM,68.0,Male,American Indian,False,PENDING,PENDING,NaN,NaN,NaN,NaN,NaN,15243 3RD AVE.,PHOENIX,-87.631849,41.611941,78496,"(41.6119409, -87.6318491)"
22632,ME2018-02105,05/02/2018 02:00:00 PM,05/02/2018 02:25:00 PM,50.0,Male,White,False,SUICIDE,GUNSHOT WOUND OF HEAD,NaN,NaN,NaN,True,NaN,640 CUMBERLAND ST,HOFFMAN ESTATES,-88.079340,42.039490,78745,"(42.0394902, -88.07934)"
22633,ME2018-02107,05/02/2018 04:53:00 PM,05/02/2018 05:11:00 PM,57.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CHRONIC OBSTRUCTIVE PULMONARY DISEASE,NaN,NaN,3914 212 PL,MATTESON,-87.711457,41.504114,78828,"(41.5041136, -87.7114567)"

## Cleaning up your data

First you'll want to convert the `Race` and `Gender` columns from codes into actual text to make analysis easier.

### Gender codes

* `-1` - `Data missing`
* `0` - `Female`
* `1` - `Male`
* `2` - `Unknown`

### Race codes

* `-1` - `Data missing`
* `0` - `American Indian`
* `1` - `Asian`
* `2` - `Black`
* `3` - `Other`
* `4` - `Unknown`
* `5` - `White`

In [8]:
#above

In [9]:
#above

## What percent of the dataset is men, and what percent is women?

It should display as **Male** and **Female**, not as numbers.

In [10]:
pctg_gender =Medical_case.Gender.value_counts(normalize=True)*100
pctg_gender

Male       71.708161
Female     28.238583
Unknown     0.053255
Name: Gender, dtype: float64

## Getting rid of "Data missing"

`Unknown` means that officially the gender or race is unknown, while `Data missing` means the record is incomplete. That means "Data missing" should have been `NaN`!

Go back to your `read_csv` many cells before and make it so that "Data missing" is automatically set as `NaN`.

- *Tip: Do not use `.replace` for this one!*
- *Tip: Look at the options for `read_csv`, there's something that lets you specify missing values*
- *Tip: It isn't `"Data missing"` - think about how you already replaced*
- *Tip: Be sure you're using an array when you tell it what the 'missing' options are*

### After you've done this, re-run all of the the previous cells and confirm that `"Data missing"` does not exist any more

## What is the most common race in the dataset? We want percentages.

We'll come back to this later, I'm just having you check the column for now.

In [11]:
pctg_race =Medical_case.Race.value_counts(normalize=True)*100
pctg_race

White              55.486450
Black              41.608174
Asian               1.519325
Other               1.195024
Unknown             0.124389
American Indian     0.066637
Name: Race, dtype: float64

## Do a `.value_counts()` on the `Opioid Related` column

In [12]:
Medical_case.dtypes

Case Number              object
Date of Incident         object
Date of Death            object
Age                     float64
Gender                   object
Race                     object
Latino                     bool
Manner of Death          object
Primary Cause            object
Primary Cause Line B     object
Primary Cause Line C     object
Secondary Cause          object
Gun Related              object
Opioid Related           object
Incident Address         object
Incident City            object
longitude               float64
latitude                float64
OBJECTID                  int64
location                 object
dtype: object

In [13]:
Medical_case = Medical_case.rename(columns={'Opioid Related':'Opioid_related', 'Case Number':'Case_number', 'Date of Incident':'Incident_date', 'Manner of Death':'Manner_of_death', 'Secondary Cause':'Secondary_cause','Incident City':'Incident_city', 'Incident Address':'Incident_address','Gun Related':'Gun_related', 'Date of Death':'Date_of_death', 'Primary Cause':'Primary_cause', 'Primary Cause Line B':'Primary_cause_line_b', 'Primary Cause Line C':'Primary_cause_line_c'})
Medical_case.head()
#df.rename(columns={
    #'T012_001': 'Total Population',
    #'T012_002': 'White'
#})

,Case_number,Incident_date,Date_of_death,Age,Gender,Race,Latino,Manner_of_death,Primary_cause,Primary_cause_line_b,Primary_cause_line_c,Secondary_cause,Gun_related,Opioid_related,Incident_address,Incident_city,longitude,latitude,OBJECTID,location
0,ME2017-04255,09/10/2017 08:28:00 PM,09/10/2017 08:51:00 PM,51.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20468,NaN
1,ME2018-02149,05/05/2018 06:30:00 AM,05/05/2018 06:41:00 AM,65.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2110 W. 21ST PL #1,CHICAGO,-87.678845,41.853279,77827,"(41.8532787, -87.6788449)"
2,ME2018-02154,04/26/2018 08:29:00 AM,05/05/2018 04:45:00 AM,95.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20704 S Woodlawn Ct,FRANKFORT,NaN,NaN,77839,NaN
3,ME2018-02156,05/05/2018 12:00:00 PM,05/05/2018 12:25:00 PM,64.0,Female,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4008 W. BERTEAU AVENUE, APT #1",CHICAGO,-87.728177,41.957468,77823,"(41.9574677, -87.7281769)"
4,ME2018-02158,05/05/2018 09:30:00 AM,05/05/2018 09:50:00 AM,61.0,Male,Black,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3947 W. LEXINGTON STREET,CHICAGO,-87.724739,41.871451,77822,"(41.8714515, -87.7247386)"

In [14]:
Opioid_case = Medical_case.Opioid_related.value_counts()
Opioid_case

True    3378
Name: Opioid_related, dtype: int64

## That's weird. Did everyone die from opioids? Try again, but including missing data.

In [15]:
Medical_case.Opioid_related.isna().value_counts()
#isna in this case is the missing data as explained above, refers also to NaN which in gender and race we replaced it into data missing

True     19256
False     3378
Name: Opioid_related, dtype: int64

## Cleaning up True/False columns

For some reason in this dataset, the True/False columns are either `True` or `NaN`. `NaN` causes a lot of problems, I'd rather have it be false.

You can use [`fillna`](http://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.DataFrame.fillna.html) to fill in empty data - it's like `.replace` but for `NaN`.

### Replace all `NaN` values with `False` for the "Gun Related" and "Opioid Related" columns.

In [16]:
Medical_case['Gun_related'].fillna("FALSE", inplace = True) 
Medical_case.Gun_related

0        FALSE
1        FALSE
2        FALSE
3        FALSE
4        FALSE
5        FALSE
6         True
7        FALSE
8        FALSE
9        FALSE
10        True
11       FALSE
12       FALSE
13       FALSE
14        True
15       FALSE
16       FALSE
17       FALSE
18       FALSE
19        True
20       FALSE
21       FALSE
22       FALSE
23       FALSE
24       FALSE
25       FALSE
26       FALSE
27       FALSE
28       FALSE
29       FALSE
         ...
22604    FALSE
22605    FALSE
22606    FALSE
22607    FALSE
22608    FALSE
22609    FALSE
22610    FALSE
22611    FALSE
22612    FALSE
22613    FALSE
22614    FALSE
22615    FALSE
22616    FALSE
22617    FALSE
22618    FALSE
22619    FALSE
22620    FALSE
22621    FALSE
22622    FALSE
22623    FALSE
22624    FALSE
22625    FALSE
22626    FALSE
22627    FALSE
22628     True
22629    FALSE
22630    FALSE
22631    FALSE
22632     True
22633    FALSE
Name: Gun_related, Length: 22634, dtype: object

In [17]:
#check Nan values
Medical_case.Gun_related.isna().value_counts()

False    22634
Name: Gun_related, dtype: int64

In [18]:
Medical_case['Opioid_related'].fillna("FALSE", inplace = True) 
Medical_case.Opioid_related

0        FALSE
1        FALSE
2        FALSE
3        FALSE
4        FALSE
5        FALSE
6        FALSE
7        FALSE
8        FALSE
9        FALSE
10       FALSE
11       FALSE
12       FALSE
13       FALSE
14       FALSE
15        True
16       FALSE
17       FALSE
18       FALSE
19       FALSE
20       FALSE
21       FALSE
22       FALSE
23       FALSE
24       FALSE
25       FALSE
26       FALSE
27       FALSE
28       FALSE
29       FALSE
         ...
22604    FALSE
22605    FALSE
22606    FALSE
22607    FALSE
22608    FALSE
22609    FALSE
22610    FALSE
22611    FALSE
22612    FALSE
22613    FALSE
22614    FALSE
22615    FALSE
22616    FALSE
22617    FALSE
22618    FALSE
22619    FALSE
22620    FALSE
22621    FALSE
22622    FALSE
22623    FALSE
22624    FALSE
22625    FALSE
22626    FALSE
22627    FALSE
22628    FALSE
22629    FALSE
22630    FALSE
22631    FALSE
22632    FALSE
22633    FALSE
Name: Opioid_related, Length: 22634, dtype: object

In [19]:
Medical_case.Opioid_related.isna().value_counts()

False    22634
Name: Opioid_related, dtype: int64

### Do another value counts on Opioid Related to make sure it has both True and False values

In [20]:
Medical_case.Opioid_related.value_counts()

FALSE    19256
True      3378
Name: Opioid_related, dtype: int64

# Back to analysis!

## What's the average age people were when they died?

In [21]:
Medical_case.dtypes

Case_number              object
Incident_date            object
Date_of_death            object
Age                     float64
Gender                   object
Race                     object
Latino                     bool
Manner_of_death          object
Primary_cause            object
Primary_cause_line_b     object
Primary_cause_line_c     object
Secondary_cause          object
Gun_related              object
Opioid_related           object
Incident_address         object
Incident_city            object
longitude               float64
latitude                float64
OBJECTID                  int64
location                 object
dtype: object

In [22]:
Medical_case.Age.mean()
#average age of people dying

51.279928793947484

## Let's look at how the oldest people died

We're just going to browse. Read through how the **oldest 30 people died.**

In [23]:
Medical_case.dropna(subset=['Age'])
#eliminate the NaN values first

,Case_number,Incident_date,Date_of_death,Age,Gender,Race,Latino,Manner_of_death,Primary_cause,Primary_cause_line_b,Primary_cause_line_c,Secondary_cause,Gun_related,Opioid_related,Incident_address,Incident_city,longitude,latitude,OBJECTID,location
0,ME2017-04255,09/10/2017 08:28:00 PM,09/10/2017 08:51:00 PM,51.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,20468,NaN
1,ME2018-02149,05/05/2018 06:30:00 AM,05/05/2018 06:41:00 AM,65.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,FALSE,FALSE,2110 W. 21ST PL #1,CHICAGO,-87.678845,41.853279,77827,"(41.8532787, -87.6788449)"
2,ME2018-02154,04/26/2018 08:29:00 AM,05/05/2018 04:45:00 AM,95.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,FALSE,FALSE,20704 S Woodlawn Ct,FRANKFORT,NaN,NaN,77839,NaN
3,ME2018-02156,05/05/2018 12:00:00 PM,05/05/2018 12:25:00 PM,64.0,Female,White,False,NaN,NaN,NaN,NaN,NaN,FALSE,FALSE,"4008 W. BERTEAU AVENUE, APT #1",CHICAGO,-87.728177,41.957468,77823,"(41.9574677, -87.7281769)"
4,ME2018-02158,05/05/2018 09:30:00 AM,05/05/2018 09:50:00 AM,61.0,Male,Black,False,NaN,NaN,NaN,NaN,NaN,FALSE,FALSE,3947 W. LEXINGTON STREET,CHICAGO,-87.724739,41.871451,77822,"(41.8714515, -87.7247386)"
5,ME2018-02153,03/20/2018 12:00:00 AM,05/05/2018 01:28:00 AM,28.0,Male,Black,False,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,77903,NaN
6,ME2017-00971,02/25/2017 07:48:00 AM,02/25/2017 09:20:00 AM,55.0,Male,White,False,UNDETERMINED,GUNSHOT WOUND TO HEAD,NaN,NaN,NaN,True,FALSE,209 E. LAKE SHORE DRIVE,CHICAGO,-87.621421,41.900571,77930,"(41.900571, -87.6214206)"
7,ME2018-02147,05/04/2018 10:04:00 PM,05/04/2018 10:25:00 PM,47.0,Male,Black,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,1905 S. SPAULDING #1,CHICAGO,-87.707465,41.855148,78042,"(41.855148, -87.707465)"
8,ME2018-02152,05/05/2018 01:47:00 AM,05/05/2018 02:54:00 AM,3.0,Male,White,True,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,1012 N. AVERS AVENUE APT#2,CHICAGO,NaN,NaN,78299,NaN
9,ME2018-02151,05/05/2018 06:00:00 AM,05/05/2018 06:35:00 AM,62.0,Male,Black,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,910 W 76TH 3RD FLOOR,CHICAGO,-87.647042,41.756124,78337,"(41.7561236, -87.6470422)"
10,ME2018-02148,05/04/2018 11:55:00 PM,05/05/2018 12:16:00 AM,55.0,Male,Black,False,SUICIDE,GUNSHOT WOUND OF HEAD,NaN,NaN,NaN,True,FALSE,"300 NORTH STATE, APT 6021",CHICAGO,-87.629078,41.887930,78480,"(41.8879298, -87.6290778)"
11,ME2014-00679,09/24/2014 09:06:00 PM,09/25/2014 01:52:00 AM,52.0,Male,White,False,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,FALSE,FALSE,724 Railroad Street,JOLIET,NaN,NaN,62692,NaN
12,ME2018-01106,03/01/2018 01:58:00 PM,03/01/2018 05:00:00 PM,37.0,Male,White,False,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,FALSE,FALSE,290 EASTBOUND AT MILE MARKER POST 14,BELLWOOD,NaN,NaN,60932,NaN
13,ME2018-01125,03/02/2018 10:45:00 PM,03/02/2018 11:09:00 PM,47.0,Male,Black,False,NATURAL,COMPLICATIONS OF MORBID OBESITY,NaN,NaN,NaN,FALSE,FALSE,1132 TROOST AVENUE APT 101,FOREST PARK,-87.816930,41.865348,77748,"(41.8653484, -87.8169297)"
14,ME2018-01126,03/03/2018 01:15:00 AM,03/03/2018 02:16:00 AM,37.0,Male,White,True,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,FALSE,159TH AND FINCH,HARVEY,-87.640104,41.600898,58723,"(41.6008977, -87.6401039)"
15,ME2018-01127,03/03/2018 02:15:00 AM,03/03/2018 02:24:00 AM,37.0,Male,White,False,ACCIDENT,"COMBINED DRUG (COCAINE, HEROIN, FENTANYL) TOXI...",NaN,NaN,NaN,FALSE,True,6547 W. 111TH APT W-27,WORTH,-87.781732,41.689640,63784,"(41.6896403, -87.7817317)"
16,ME2018-01128,03/03/2018 02:51:00 AM,03/03/2018 03:13:00 AM,31.0,Male,Black,False,HOMICIDE,MULTIPLE SHARP FORCE INJURIES,NaN,NaN,NaN,FALSE,FALSE,6916 S. MICHIGAN AVENUE,CHICAGO,-87.622115,41.768692,77583,"(41.7686918, -87.6221153)"
17,ME2018-01130,02/17/2018 12:00:00 AM,03/02/2018 11:31:00 PM,66.0,Male,White,False,ACCIDENT,CLOSED HEAD INJURIES,NaN,NaN,CHRONIC ETHANOLISM,FALSE,FALSE,6238 w. 26th #205,BERWYN,-87.780093,41.843267,57453,"(41.8432672, -87.7800927)"
18,ME2018-01135,03/03/2018 09:30:00 AM,03/03/2018 10:05:00 AM,55.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,FALSE,FALSE,10034 S. MICHICAGN AVE. APT 2,NaN,NaN,NaN,71064,NaN
19,ME2018-02093,05/01/2018 11:00:00 PM,05/01/2018 10:22:00 PM,31.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,FALSE,4811 W. WASHINGTON BLVD.,CHICAGO,-87.745651,41.881767,77825,"(41.8817674, -87.7456512)"
20,ME2018-02096,05/02/2018 02:58:00 AM,05/02/2018 03:41:00 AM,69.0,Male,White,False,HOMICIDE,MULTIPLE STAB AND INCISED WOUNDS,NaN,NaN,NaN,FALSE,FALSE,5300 S. SOUTH SHORE DRIVE UNIT 43,CHICAGO,NaN,NaN,77978,NaN
21,ME2018-02125,05/01/2018 01:00:00 PM,05/03/2018 01:52:00 PM,49.0,Female,White,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,1653 W Congress Pkwy,NaN,-87.667945,41.875108,78013,"(41.8751081, -87.6679448)"
22,ME2018-02095,05/01/2018 11:00:00 PM,05/01/2018 11:59:00 PM,37.0,Male,Black,False,HOMICIDE,STAB WOUND OF CHEST,NaN,NaN,NaN,FALSE,FALSE,1440 EMBASSY LANE,FORD HEIGHTS,-87.585216,41.513330,78840,"(41.5133297, -87.5852155)"
23,ME2014-00102,08/17/2014 12:00:00 PM,08/17/2014 03:11:00 PM,39.0,Female,Black,False,SUICIDE,MULTIPLE INJURIES,NaN,NaN,NaN,FALSE,FALSE,"23443 WESTERN AVENUE, APT. 72",PARK FOREST,NaN,NaN,63896,NaN
24,ME2014-00339,09/02/2014 08:14:00 PM,09/03/2014 04:13:00 AM,54.0,Male,White,False,ACCIDENT,CEREBRAL INJURIES,NaN,NaN,NaN,FALSE,FALSE,IRVING PARK RD AT SALT CREEK,WOOD DALE,NaN,NaN,62191,NaN
25,ME2018-02136,05/03/2018 09:05:00 PM,05/03/2018 09:47:00 PM,53.0,Male,Black,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,"8301 SOUTH 88TH AVE, APT 412",JUSTICE,NaN,NaN,77854,NaN
26,ME2018-02166,04/30/2018 03:00:00 PM,05/06/2018 06:09:00 AM,66.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,FALSE,FALSE,1815 N. KARLOV,CHICAGO,-87.728637,41.914066,77857,"(41.9140656, -87.7286374)"
27,ME2018-02131,05/03/2018 07:15:00 PM,05/03/2018 08:00:00 PM,48.0,Male,White,False,NATURAL,ATHEROSCLEROTIC AND HYPERTENSIVE CARDIOVASCULA...,NaN,NaN,OBESITY,FALSE,FALSE,2631 West Rascher Avenue,CHICAGO,-87.695479,41.980215,77843,"(41.9802154, -87.6954789)"
28,ME2018-02134,05/03/2018 06:20:00 PM,05/03/2018 07:01:00 PM,76.0,Male,White,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,DIABETES MELLITUS AND OBESITY,FALSE,FALSE,8108 ODELL AVENUE,BRIDGEVIEW,-87.803607,41.744014,77849,"(41.7440145, -87.8036075)"
29,ME2018-02177,05/07/2018 04:16:00 AM,05/07/2018 05:07:00 AM,49.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,FALSE,FALSE,411 Carrick Rd,MATTESON,-87.729948,41.518675,77881,"(41.5186752, -87.7299482)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22603,ME2018-02087,04/14/2018 03:00:00 PM,05/01/2018 05:47:00 PM,78.0,Male,Asian,False,ACCIDENT,COMPLICATIONS OF FALL,NaN,NaN,NaN,FALSE,FALSE,"1475 REBECCA DRIVE, UNIT 420",HOFFMAN ESTATES,-88.125064,42.052463,58537,"(42.0524629, -88.1250639)"
22604,ME2018-02088,05/01/2018 05:15:00 PM,05/01/2018 06:50:00 PM,50.0,Male,White,True,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,"DIABETES MELLITUS, CIRRHOSIS OF THE LIVER",FALSE,FALSE,"2832 WEST CERMAK, UNIT 2F",CHICAGO,-87.696780,41.852127,70244,"(41.8521269, -87.6967797)"
22606,ME2018-02090,05/01/2018 07:20:00 PM,05/01/2018 06:29:00 PM,48.0,Female,Black,False,NATURAL,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,NaN,NaN,CHRONIC KIDNEY DISEASE,FALSE,FALSE,201 W. 69TH STREET,CHICAGO,-87.630248,41.768766,72642,"(41.768766, -87.6302482)"
22607,ME2018-02092,05/01/2018 10:30:00 PM,05/01/2018 10:38:00 PM,48.0,Male,Black,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,7846 S Kingston,CHICAGO,-87.562686,41.752230,77795,"(41.7522303, -87.5626855)"
22608,ME2018-02074,05/01/2018 08:33:00 AM,05/01/2018 09:03:00 AM,62.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,FALSE,FALSE,2901 S. Michigan Avenue #504 South Commons,CHICAGO,-87.622834,41.841718,77971,"(41.8417184, -87.6228345)"
22609,ME2018-02099,05/02/2018 09:45:00 AM,05/02/2018 09:49:00 AM,30.0,Male,Black,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,250 N. Western Avenue,NaN,-87.686970,41.886049,77976,"(41.8860494, -87.6869702)"
22610,ME2018-02098,05/02/2018 06:00:00 AM,05/02/2018 06:39:00 AM,56.0,Male,Black,False,HOMICIDE,MULTIPLE BLUNT FORCE INJURIES,NaN,NaN,NaN,FALSE,FALSE,216 w. 147TH STREET,HARVEY,-87.668955,41.622493,78086,"(41.6224931, -87.6689548)"
22611,ME2018-02091,05/01/2018 08:00:00 PM,05/01/2018 08:45:00 PM,55.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CIRRHOSIS OF UNKNOWN ETIOLOGY,FALSE,FALSE,1755 HENLEY ST #2N,GLENVIEW,-87.802212,42.070070,78280,"(42.0700695, -87.8022124)"
22612,ME2018-02081,05/01/2018 12:40:00 PM,05/01/2018 12:53:00 PM,61.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,FALSE,FALSE,"527 W. 14TH PLACE, PACIFIC GARDEN MISSION",CHICAGO,-87.640188,41.862401,78381,"(41.8624014, -87.640188)"
22613,ME2018-02094,05/01/2018 09:10:00 PM,05/01/2018 10:12:00 PM,54.0,Male,White,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,9858 IRVING PARK ROAD,SCHILLER PARK,-87.873368,41.956126,78475,"(41.9561261, -87.8733682)"
22614,ME2018-02097,05/02/2018 06:00:00 AM,05/02/2018 06:49:00 AM,53.0,Female,Black,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,2373 E 70TH ST,CHICAGO,-87.567272,41.768022,78635,"(41.768022, -87.5672724)"
22615,ME2018-02101,05/02/2018 07:00:00 AM,05/02/2018 10:03:00 AM,43.0,Male,White,True,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,9558 SHERMER ROAD,MORTON GROVE,-87.811772,42.054776,77791,"(42.0547758, -87.8117716)"
22616,ME2018-02103,04/30/2018 12:00:00 AM,05/02/2018 01:21:00 PM,77.0,Male,White,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,"1001 Elm Street, South West",DEMOTTE,NaN,NaN,57915,NaN
22617,ME2018-02109,05/02/2018 05:00:00 PM,05/02/2018 05:18:00 PM,59.0,Male,White,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,529 RIDGEWOOD ROAD,ELK GROVE VILLAGE,-87.982034,42.018169,77811,"(42.0181695, -87.982034)"
22618,ME2018-02110,05/02/2018 07:50:00 PM,05/02/2018 08:14:00 PM,72.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,FALSE,FALSE,"1341 W. 92ND STREET, UNIT #2",CHICAGO,-87.657078,41.726717,77789,"(41.7267165, -87.6570785)"
22619,ME2018-02111,05/02/2018 09:17:00 PM,05/02/2018 09:23:00 PM,91.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,FALSE,FALSE,2058 W. Hutchinson,CHICAGO,-87.681238,41.958973,67932,"(41.9589732, -87.6812383)"
22620,ME2018-02116,04/21/2018 10:00:00 PM,05/03/2018 12:15:00 PM,88.0,Male,Black,False,NaN,NaN,NaN,NaN,NaN,FALSE,FALSE,7140 S. MARSHFIELD AVENUE,CHICAGO,-87.665268,41.763703,59566,"(41.7637034, -87.6652684)"
22621,ME2018-02118,05/03/2018 08:00:00 AM,05/03/2018 09:57:00 AM,29.0,Female,White,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,9000 West College Park way,PALOS HILLS,-87.837735,41.689509,77788,"(41.6895094, -87.837735)"
22622,ME2018-02124,05/03/2018 03:09:00 PM,05/03/2018 11:33:00 AM,60.0,Female,Black,False,NaN,NaN,NaN,NaN,NaN,FALSE,FALSE,8419 S ESCANABA AVE,NaN,-87.553689,41.742221,67087,"(41.7422211, -87.5536891)"
22623,ME2018-02126,05/03/2018 02:01:00 PM,05/03/2018 02:37:00 PM,61.0,Male,White,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,1512 SILVER LANE APT #1,PALATINE,-88.007342,42.136492,77779,"(42.1364923, -88.0073415)"
22624,ME2018-02100,05/02/2018 08:08:00 AM,05/02/2018 08:21:00 AM,85.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,FALSE,FALSE,1127 Miller Lane;,BUFFALO GROVE,-87.978407,42.134728,77891,"(42.1347284, -87.9784066)"
22625,ME2018-02102,05/02/2018 12:10:00 PM,05/02/2018 12:19:00 PM,73.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,FALSE,FALSE,"549 W. ALDINE AVENUE, UNIT #203",CHICAGO,-87.643876,41.941953,77939,"(41.9419529, -87.6438762)"
22626,ME2018-02115,05/03/2018 08:32:00 AM,05/03/2018 08:52:00 AM,0.0,Female,Black,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,16102 RICHMOND AVE,MARKHAM,-87.687286,41.597228,78018,"(41.5972276, -87.687286)"
22627,ME2018-02120,05/03/2018 11:00:00 AM,05/03/2018 12:18:00 PM,32.0,Female,Black,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,9158 S. HARVARD AVENUE,CHICAGO,-87.632148,41.727769,77985,"(41.7277694, -87.6321484)"
22628,ME2018-02123,05/03/2018 01:15:00 PM,05/03/2018 01:51:00 PM,42.0,Male,Black,False,HOMICIDE,GUNSHOT WOUND OF RIGHT BUTTOCK,NaN,NaN,NaN,True,FALSE,8159 SOUTH CORNELL AVENUE,CHICAGO,-87.583910,41.746488,78103,"(41.7464877, -87.5839097)"
22629,ME2018-02104,12/31/2017 11:23:00 PM,05/02/2018 01:59:00 PM,34.0,Male,White,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,5535 NORTH LINCOLN AVENUE,CHICAGO,-87.693476,41.982498,78129,"(41.9824976, -87.6934761)"
22630,ME2018-02122,05/03/2018 12:29:00 PM,05/03/2018 12:39:00 PM,94.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,"CORONARY ARTERY DISEASE, HYPERTENSION, DIABETE...",FALSE,FALSE,16416 EVANS AVENUE,SOUTH HOLLAND,-87.600994,41.596634,78272,"(41.5966344, -87.6009945)"
22631,ME2018-02114,05/03/2018 08:09:00 AM,05/03/2018 08:19:00 AM,68.0,Male,American Indian,False,PENDING,PENDING,NaN,NaN,NaN,FALSE,FALSE,15243 3RD AVE.,PHOENIX,-87.631849,41.611941,78496,"(41.6119409, -87.6318491)"
22632,ME2018-02105,05/02/2018 02:00:00 PM,05/02/2018 02:25:00 PM,50.0,Male,White,False,SUICIDE,GUNSHOT WOUND OF HEAD,NaN,NaN,NaN,True,FALSE,640 CUMBERLAND ST,HOFFMAN ESTATES,-88.079340,42.039490,78745,"(42.0394902, -88.07934)"
22633,ME2018-02107,05/02/2018 04:53:00 PM,05/02/2018 05:11:00 PM,57.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CHRONIC OBSTRUCTIVE PULMONARY DISEASE,FALSE,FALSE,3914 212 PL,MATTESON,-87.711457,41.504114,78828,"(41.5041136, -87.7114567)"

In [42]:
Medical_case.Age.dropna().astype(int).value_counts()
#Medical_case.Age.value_counts().sort_values(ascending=False)

58     527
57     507
55     503
56     500
59     499
54     484
62     461
61     444
60     444
51     431
63     426
53     425
52     422
64     418
50     381
47     380
49     368
65     362
0      350
48     347
67     337
25     329
45     329
66     321
68     318
26     309
44     303
46     302
28     299
43     286
      ...
16     107
91     106
92      90
93      88
94      74
15      74
95      46
1       39
96      35
97      33
2       32
14      26
98      25
99      18
13      17
3       16
12      15
4       14
100     14
5       14
10      13
11      12
9       11
6       11
8        9
7        7
101      6
103      3
106      2
105      1
Name: Age, Length: 105, dtype: int64

In [38]:
Medical_case.Age.value_counts().sort_values(ascending=False)

58.0     527
57.0     507
55.0     503
56.0     500
59.0     499
54.0     484
62.0     461
60.0     444
61.0     444
51.0     431
63.0     426
53.0     425
52.0     422
64.0     418
50.0     381
47.0     380
49.0     368
65.0     362
0.0      350
48.0     347
67.0     337
45.0     329
25.0     329
66.0     321
68.0     318
26.0     309
44.0     303
46.0     302
28.0     299
43.0     286
        ...
16.0     107
91.0     106
92.0      90
93.0      88
15.0      74
94.0      74
95.0      46
1.0       39
96.0      35
97.0      33
2.0       32
14.0      26
98.0      25
99.0      18
13.0      17
3.0       16
12.0      15
4.0       14
100.0     14
5.0       14
10.0      13
11.0      12
9.0       11
6.0       11
8.0        9
7.0        7
101.0      6
103.0      3
106.0      2
105.0      1
Name: Age, Length: 105, dtype: int64

## Seems like a lot of problems with fractures

### What's the median age of someone dying from a cause that involves a fracture?

Are fractures especially dangerous for the elderly?

- *Tip: Filter for a cause that involves a fracture, then take the median age*
- *Tip: If you get a "cannot index NA values" error, the problem is it's trying to search `NaN` values and doesn't know what to do with them. You need to tell pandas to count `NaN` as false by setting another option - it isn't `NaN=False`, but it's close!*

In [124]:
Medical_case['Manner_of_death'].fillna("FALSE", inplace = True) 
Medical_case.Manner_of_death

0               FALSE
1               FALSE
2               FALSE
3               FALSE
4               FALSE
5            ACCIDENT
6        UNDETERMINED
7             PENDING
8             PENDING
9             PENDING
10            SUICIDE
11           ACCIDENT
12           ACCIDENT
13            NATURAL
14           HOMICIDE
15           ACCIDENT
16           HOMICIDE
17           ACCIDENT
18            NATURAL
19           HOMICIDE
20           HOMICIDE
21            PENDING
22           HOMICIDE
23            SUICIDE
24           ACCIDENT
25            PENDING
26              FALSE
27            NATURAL
28            NATURAL
29              FALSE
             ...
22604         NATURAL
22605           FALSE
22606         NATURAL
22607         PENDING
22608         NATURAL
22609         PENDING
22610        HOMICIDE
22611         NATURAL
22612         NATURAL
22613         PENDING
22614         PENDING
22615         PENDING
22616         PENDING
22617         PENDING
22618         NATURAL
22619         NATURAL
22620           FALSE
22621         PENDING
22622           FALSE
22623         PENDING
22624         NATURAL
22625         NATURAL
22626         PENDING
22627         PENDING
22628        HOMICIDE
22629         PENDING
22630         NATURAL
22631         PENDING
22632         SUICIDE
22633         NATURAL
Name: Manner_of_death, Length: 22634, dtype: object

In [55]:
fractures_death = Medical_case[Medical_case.Manner_of_death.str.contains('FRACTURES')]
fractures_death

ValueError: cannot index with vector containing NA / NaN values

### To get a "compared to what?", what's the median age of _anyone_ dying an accidental death?

In [50]:
accidental_death = Medical_case[Medical_case.Manner_of_death=='ACCIDENT']
accidental_death.head()

,Case_number,Incident_date,Date_of_death,Age,Gender,Race,Latino,Manner_of_death,Primary_cause,Primary_cause_line_b,Primary_cause_line_c,Secondary_cause,Gun_related,Opioid_related,Incident_address,Incident_city,longitude,latitude,OBJECTID,location
5,ME2018-02153,03/20/2018 12:00:00 AM,05/05/2018 01:28:00 AM,28.0,Male,Black,False,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,77903,NaN
11,ME2014-00679,09/24/2014 09:06:00 PM,09/25/2014 01:52:00 AM,52.0,Male,White,False,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,FALSE,FALSE,724 Railroad Street,JOLIET,NaN,NaN,62692,NaN
12,ME2018-01106,03/01/2018 01:58:00 PM,03/01/2018 05:00:00 PM,37.0,Male,White,False,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,FALSE,FALSE,290 EASTBOUND AT MILE MARKER POST 14,BELLWOOD,NaN,NaN,60932,NaN
15,ME2018-01127,03/03/2018 02:15:00 AM,03/03/2018 02:24:00 AM,37.0,Male,White,False,ACCIDENT,"COMBINED DRUG (COCAINE, HEROIN, FENTANYL) TOXI...",NaN,NaN,NaN,FALSE,True,6547 W. 111TH APT W-27,WORTH,-87.781732,41.689640,63784,"(41.6896403, -87.7817317)"
17,ME2018-01130,02/17/2018 12:00:00 AM,03/02/2018 11:31:00 PM,66.0,Male,White,False,ACCIDENT,CLOSED HEAD INJURIES,NaN,NaN,CHRONIC ETHANOLISM,FALSE,FALSE,6238 w. 26th #205,BERWYN,-87.780093,41.843267,57453,"(41.8432672, -87.7800927)"

In [52]:
median_age_accident = accidental_death.Age.median()
median_age_accident

51.0

### What's the median age of each manner of death?

It looks like different kinds of death might happen to different ages of people. Let's investigate that further.

In [56]:
Medical_case.Manner_of_death.value_counts()

NATURAL         9220
ACCIDENT        7627
HOMICIDE        2839
SUICIDE         1711
UNDETERMINED     502
PENDING          459
Name: Manner_of_death, dtype: int64

### Who is the oldest homicide victim?

It looks like homicide is for young people, so maybe we'll find an interesting outlier?

## Investigating toxicity-related homicides

She was old, and was purposefully overdosed on morphine and hydrocodone. Might have been euthenasia? Let's find similar cases.

### Find every homicide where the primary cause of death is some sort of toxicity

Toxicity can just overdose. You should have **ten rows**.

- *Tip: If you're doing this as one statement, make sure you use your parentheses correctly. If you leave them out, you'll have zero rows*
- *Tip: You could make a homicides-only dataframe if you wanted to*

### Okay, nope, we were wrong.

Those were almost **all from fires**. Apparently homicide is not the best place to go looking for toxicity. What's the most popular manner of death for primary causes involving toxicity?

- *Tip: Remember that `['colname']` is the same as `.colname`. You can't do `.col with spaces` so you'll need to do `['col with spaces']` a lot in this dataset
- *Tip: Or I guess if you really wanted to, you could rename your columns to have spaces in them (IF YOU DO THIS DON'T DO IT IN EXCEL BECAUSE IT WILL PROBABLY BREAK YOUR CSV.)*

### Okay, toxicity deaths (overdoses) are mostly accidents. Let's look at the first 30 accidental deaths involving toxicity.

- *Tip: Remember your parentheses!*

## Wow, that's a lot of drug overdoses. What's more popular for overdosing: heroin, fentanyl, cocaine, or ethanol?

You can count something like "COMBINED ETHANOL, NORDIAZEPAM, AND FENTANYL TOXICITY" under both ethanol and fentanyl.

- *Tip: Search for them individually*

# Cleaning up Primary Cause

Let's stop investigating for a second and maybe clean up this "Primary Cause" column.

## What are the most common Primary Cause of death? Include `NaN` values

- *Tip: There is an option that keeps `NaN` values when counting things in a column.*

## That was horrible looking. I don't want to read through that - how many `NaN` causes of death are there?

- *Tip: You can use `isnull()` to see if it's missing data, but how do you count the results?*

## Remove all rows where the primary cause of death has not been filled out.

- *Tip: confirm that you have 22510 rows when you're done*

# Cardiovascular disease

Cardiovascular disease (heart disease) is the number one or number two killer in America.

### Filter for only rows where cardiovascular disease was a primary cause

- *Tip: I hope you know how to deal with the `NaN` error message by now!*

### What are the different types?

### Replace all of those with a nice simple 'CARDIOVASCULAR DISEASE'

- *Tip: you can use `.replace` or `.str.replace`, but they each involve different things! I suggest `.replace`, it looks a little cleaner in this situation*
- *Tip: for `.replace`, you need to give it more options than usual*
- *Tip: for `.str.replace`, it won't automatically save back into the column, you need to do that yourself*

### Check the top 5 primary causes. Cardiovascular disease should be first with about 28.4%

We could also clean up gunshots, but... let's just move on.

# The Opioid Epidemic

America has a [big problem with fentanyl](https://www.theatlantic.com/health/archive/2018/05/americas-opioid-crisis-is-now-a-fentanyl-crisis/559445/) and other opioids.

## Find all of the rows where fentanyl was part of the primary cause of death

We don't need `na=False` any more because we *dropped the rows without primary causes*.

## Fentanyl and race

In the late 80's and 90's, the [crack cocaine epidemic](https://en.wikipedia.org/wiki/Crack_epidemic) swept through inner cities in the US. It was treated primarily as a crime problem, while many people say fentanyl and heroin overdoses are being treated as a medical problem due to the racial differences - the crack epidemic mainly affected Black communities, while fentanyl seems to be a problem for everyone.

### How does the racial breakdown of fentanyl deaths compare to the racial breakdown of other causes of death? How about compared to causes of accidental death?

### Now compare it to homicides

### Now compare it to suicide

## These differences seems kind of crazy

Let's look at all of these at once: I want a breakdown of the most common manners of death for **men**, based on race.

Percentages, please, not raw numbers.

You can look at women, too, although I think the numbers are more surprising for men.

## Back to drugs: what is the most popular opioid-related primary cause of death that does NOT involve fentanyl?

- *Tip: Pay attention to your column names! There's one that might tell you if something is opioid-related...*
- *Tip: Usually you can use `not` or `!` to means "not", but for pandas and `.isin` or `.str.contains` you need to use `~`*
- *Tip: For "and" in pandas you'll need to use `&`, and make sure all of your clauses have parens around them, e.g. `df[(df.col1 = 'A') & (df.col2 = 'B')]`.*

# How do heroin and fentanyl deaths compare?

## Count the number of deaths involving heroin, the number of deaths involving fentanyl, and the number of deaths involving both.

- *Tip: This will take 3 different statements*
- *Tip: You should get `813` that include both*

## That's weird.

I heard fentanyl really surpassed heroin in the past few years. Let's see how this 

### Pull the year out and store it in a new column called `year`

If you run `df['Date of Incident'].str.extract("(\d\d\d\d)", expand=False)`, it will pull out the year of each incident. **Store this in a new column called `year`.**

(It's regular expression stuff. `\d\d\d\d` means "four numbers in a row", and `()` + `.str.extract` means "pull it out".)

### What is the datatype of the new `year` column?

## Convert this new column to an integer and save it back on top of itself

- *Tip: This uses is your friend `.astype`*
- *Tip: Make sure to save it back on top of itself!*

## Confirm the column is a number

## Plot the number of opioid deaths by year

If you'd like to make it look nicer, do some sorting and get rid of 2018.

- *Tip: Think of it in a few steps. First, filter for opioid deaths. Then get the number of deaths for each year. Then plot it.*
- *Tip: What's up with 2018? Why's it look so weird? Can you get rid of it? Remember to use lots of parens!*
- *Tip: Make sure the earliest year is on the left. You might need to sort by something other than values.*

## Plot the number of fentanyl deaths by year, and the number of heroin deaths by year

- *Tip: You'll want to look up how to use `ylim` - it will let you set each graphic to use the same scale. This should be separate graphics.*
- *Tip: Pay attention to the numbers on your axes. `sort_index()` will be your friend.*
- *Tip: You should probably get rid of 2018*

## How does this compare to gun deaths?

## But hey: numbers can lie pretty easily!

The numbers are just so low in 2014 and much higher in 2017. What's going on there?

Well, maybe **there just isn't as much data from the earlier years**. Plot how many entries there are for each year.

And we don't know the best way to fix that up yet, so instead I'm going to give you a present.

# Is the true lesson here, don't move to Cook County, Illinois?

Cook County is basically Chicago. It's probably just certain areas that are trouble, right? Let's investigate that without even having a clue how mapping works.

## Fun bonus: Making cheating maps

### Make a new dataframe of every death in the actual city of Chicago

### Confirm this new dataframe has 13,627 rows

### Use lat and long in the worst way possible to make a map

Use `longitude` and `latitude` and `plot` to make a rough map of the city. Chicago [looks like this](https://en.wikipedia.org/wiki/File:DuPage_County_Illinois_Incorporated_and_Unincorporated_areas_Chicago_Highlighted.svg)

- *Tip: Use the `latitude` and `longitude` columns*
- *Tip: You don't want a line graph, of course. Or a bar. What kind is the kind with dots on it?*
- *Tip: Use something like like `figsize=(10,5)` to specify the height and width of the map (but, you know, with better numbers that make it look like chicago)*

## Now let's find out where to live

Make a map of every non-homicide death in Chicago, then plot the homicides on top of it.

Use the `ax=df.plot` trick from the beer cans assignment to plot all of the rows representing homicides vs non-homicides. You can use `color='red'` to make one of them red, and `alpha=0.05` to make each mark very transparent to allow them to layer on top of each other.

## Never tell anyone I let you do that.

But you want to see something actually completely legitimately insane?

**Chicago is one of the most segregated cities in America.** If you'd like to see this for yourself, make a map of `Race`. Plot black vs white in a way similar to what we did above.

Yup.