# Census Data

* **Inspo:** https://www.nytimes.com/2019/05/01/upshot/all-white-neighborhoods-are-dwindling-as-america-grows-more-diverse.html
* **Datasets:**
    - `1980.csv` - table for 1980
    - `1980.txt` - codebook
    - same for `1990`, `2000`, `2010`
* **Source:** Social Explorer, which you can access through https://library.columbia.edu
* **Topics:**
    - LOL @ the US government
    - renaming columns
    - a real fun way to import data
    - a real fun way to rename columns
    - census data

In [1]:
import pandas as pd
%matplotlib inline

In [2]:
df = pd.read_csv('1980.csv', encoding='latin-1')
df.head()

,Geo_FIPS,Geo_NAME,Geo_QName,Geo_NATION,Geo_STATE,Geo_COUNTY,Geo_CT,SE_T012_001,SE_T012_002,SE_T012_003,SE_T012_004,SE_T012_005,SE_T012_006
0,1001020100,Census Tract 201,"Census Tract 201, Autauga County, Alabama",0,1,1,20100,1583.979102,1543.979630,31.999578,2.99996,4.999934,0.000000
1,1001020200,Census Tract 202,"Census Tract 202, Autauga County, Alabama",0,1,1,20200,2233.000029,840.000011,1388.000018,0.00000,3.000000,2.000000
2,1001020300,Census Tract 203,"Census Tract 203, Autauga County, Alabama",0,1,1,20300,3136.000025,2634.000021,467.000004,12.00000,19.000000,4.000000
3,1001020400,Census Tract 204,"Census Tract 204, Autauga County, Alabama",0,1,1,20400,4927.999972,4889.999972,1.000000,8.00000,10.000000,19.000000
4,1001020500,Census Tract 205,"Census Tract 205, Autauga County, Alabama",0,1,1,20500,1531.185570,1430.276440,70.388402,6.99304,8.286086,15.241602

In [3]:
df.columns = df.columns.str.replace("SE_","") #jangan lupa setiap ganti sesuatu replace safe it dengan variable baru. apa yang mau diganti ditaruh di bagian kiri. df.columns
df.head()

,Geo_FIPS,Geo_NAME,Geo_QName,Geo_NATION,Geo_STATE,Geo_COUNTY,Geo_CT,T012_001,T012_002,T012_003,T012_004,T012_005,T012_006
0,1001020100,Census Tract 201,"Census Tract 201, Autauga County, Alabama",0,1,1,20100,1583.979102,1543.979630,31.999578,2.99996,4.999934,0.000000
1,1001020200,Census Tract 202,"Census Tract 202, Autauga County, Alabama",0,1,1,20200,2233.000029,840.000011,1388.000018,0.00000,3.000000,2.000000
2,1001020300,Census Tract 203,"Census Tract 203, Autauga County, Alabama",0,1,1,20300,3136.000025,2634.000021,467.000004,12.00000,19.000000,4.000000
3,1001020400,Census Tract 204,"Census Tract 204, Autauga County, Alabama",0,1,1,20400,4927.999972,4889.999972,1.000000,8.00000,10.000000,19.000000
4,1001020500,Census Tract 205,"Census Tract 205, Autauga County, Alabama",0,1,1,20500,1531.185570,1430.276440,70.388402,6.99304,8.286086,15.241602

In [4]:
codes = pd.read_csv('1980.txt', sep=':   ', skiprows=41, nrows=12, names=['code','name'])
codes
#kalau mau ganti nama column pakai names=['code', 'name']

/Users/dronejournalismlab/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

        code                                               name
0       FIPS                                               FIPS
1       NAME                                       Name of Area
2      QName                                    Qualifying Name
3     NATION                                             Nation
4      STATE                                              State
5     COUNTY                                             County
6         CT                                       Census Tract
7   T012_001                                   Total Population
8   T012_002                            Total Population: White
9   T012_003                            Total Population: Black
10  T012_004      Total Population: American Indian, Eskimo,...
11  T012_005       Total Population: Asian and Pacific Islander

In [5]:
codes['name']= codes.name.str.strip()
#remove blank space from both sides of our name
codes_dict=dict(zip(codes.code,codes.name))
codes_dict
#buat jadi dictionary

{'FIPS': 'FIPS',
 'NAME': 'Name of Area',
 'QName': 'Qualifying Name',
 'NATION': 'Nation',
 'STATE': 'State',
 'COUNTY': 'County',
 'CT': 'Census Tract',
 'T012_001': 'Total Population',
 'T012_002': 'Total Population: White',
 'T012_003': 'Total Population: Black',
 'T012_004': 'Total Population: American Indian, Eskimo, and Aleut',
 'T012_005': 'Total Population: Asian and Pacific Islander'}

In [6]:
df=df.rename(columns=codes_dict)
df.head()

,Geo_FIPS,Geo_NAME,Geo_QName,Geo_NATION,Geo_STATE,Geo_COUNTY,Geo_CT,Total Population,Total Population: White,Total Population: Black,"Total Population: American Indian, Eskimo, and Aleut",Total Population: Asian and Pacific Islander,T012_006
0,1001020100,Census Tract 201,"Census Tract 201, Autauga County, Alabama",0,1,1,20100,1583.979102,1543.979630,31.999578,2.99996,4.999934,0.000000
1,1001020200,Census Tract 202,"Census Tract 202, Autauga County, Alabama",0,1,1,20200,2233.000029,840.000011,1388.000018,0.00000,3.000000,2.000000
2,1001020300,Census Tract 203,"Census Tract 203, Autauga County, Alabama",0,1,1,20300,3136.000025,2634.000021,467.000004,12.00000,19.000000,4.000000
3,1001020400,Census Tract 204,"Census Tract 204, Autauga County, Alabama",0,1,1,20400,4927.999972,4889.999972,1.000000,8.00000,10.000000,19.000000
4,1001020500,Census Tract 205,"Census Tract 205, Autauga County, Alabama",0,1,1,20500,1531.185570,1430.276440,70.388402,6.99304,8.286086,15.241602

In [8]:
df['pct_white'] = df['Total Population: White'] / df['Total Population']
df.head()

,Geo_FIPS,Geo_NAME,Geo_QName,Geo_NATION,Geo_STATE,Geo_COUNTY,Geo_CT,Total Population,Total Population: White,Total Population: Black,"Total Population: American Indian, Eskimo, and Aleut",Total Population: Asian and Pacific Islander,T012_006,pct_white
0,1001020100,Census Tract 201,"Census Tract 201, Autauga County, Alabama",0,1,1,20100,1583.979102,1543.979630,31.999578,2.99996,4.999934,0.000000,0.974747
1,1001020200,Census Tract 202,"Census Tract 202, Autauga County, Alabama",0,1,1,20200,2233.000029,840.000011,1388.000018,0.00000,3.000000,2.000000,0.376176
2,1001020300,Census Tract 203,"Census Tract 203, Autauga County, Alabama",0,1,1,20300,3136.000025,2634.000021,467.000004,12.00000,19.000000,4.000000,0.839923
3,1001020400,Census Tract 204,"Census Tract 204, Autauga County, Alabama",0,1,1,20400,4927.999972,4889.999972,1.000000,8.00000,10.000000,19.000000,0.992289
4,1001020500,Census Tract 205,"Census Tract 205, Autauga County, Alabama",0,1,1,20500,1531.185570,1430.276440,70.388402,6.99304,8.286086,15.241602,0.934097

In [9]:
df['pct_white'] = df['Total Population: White'] / df['Total Population']
df.head()

,Geo_FIPS,Geo_NAME,Geo_QName,Geo_NATION,Geo_STATE,Geo_COUNTY,Geo_CT,Total Population,Total Population: White,Total Population: Black,"Total Population: American Indian, Eskimo, and Aleut",Total Population: Asian and Pacific Islander,T012_006,pct_white
0,1001020100,Census Tract 201,"Census Tract 201, Autauga County, Alabama",0,1,1,20100,1583.979102,1543.979630,31.999578,2.99996,4.999934,0.000000,0.974747
1,1001020200,Census Tract 202,"Census Tract 202, Autauga County, Alabama",0,1,1,20200,2233.000029,840.000011,1388.000018,0.00000,3.000000,2.000000,0.376176
2,1001020300,Census Tract 203,"Census Tract 203, Autauga County, Alabama",0,1,1,20300,3136.000025,2634.000021,467.000004,12.00000,19.000000,4.000000,0.839923
3,1001020400,Census Tract 204,"Census Tract 204, Autauga County, Alabama",0,1,1,20400,4927.999972,4889.999972,1.000000,8.00000,10.000000,19.000000,0.992289
4,1001020500,Census Tract 205,"Census Tract 205, Autauga County, Alabama",0,1,1,20500,1531.185570,1430.276440,70.388402,6.99304,8.286086,15.241602,0.934097

In [10]:
df.pct_white

0        0.974747
1        0.376176
2        0.839923
3        0.992289
4        0.934097
5        0.803399
6        0.932092
7        0.789803
8        0.788549
9        0.765748
10       0.669890
11       0.337000
12       0.616091
13       0.939794
14       0.781021
15       0.934718
16       0.915911
17       0.615986
18       0.846408
19       0.846398
20       0.846408
21       0.846408
22       0.573899
23       0.936856
24       0.936856
25       0.936856
26       0.936856
27       0.903379
28       0.926125
29       0.926125
           ...
73972         NaN
73973         NaN
73974         NaN
73975         NaN
73976         NaN
73977         NaN
73978         NaN
73979         NaN
73980         NaN
73981         NaN
73982         NaN
73983         NaN
73984         NaN
73985         NaN
73986         NaN
73987         NaN
73988         NaN
73989         NaN
73990         NaN
73991         NaN
73992         NaN
73993         NaN
73994         NaN
73995         NaN
73996         NaN
73997         NaN
73998         NaN
73999         NaN
74000         NaN
74001         NaN
Name: pct_white, Length: 74002, dtype: float64